version: "3.9"

services:

#  rails_api:
#    container_name: rails_api
#    build: .
#    volumes:
#      - "./:/app/"
#      - "./log:/app/log"
#    ports:
#      - "3000:3000"
#    command: bash -c "rails s -b 0.0.0.0"
#    restart: unless-stopped

  db:
    image: postgres:alpine
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_USER: '${USER}'
    ports:
      - "5432:5432"

  redis:
    image: redis:4.0.14
    command: redis-server
    ports:
      - "6379:6379"
