require_relative 'slash_commands/default'
require_relative 'slash_commands/ping'
require_relative 'slash_commands/quiz'
require_relative 'slash_commands/modal'
require_relative 'slash_commands/sign_in'
require_relative 'slash_commands/bet'